version: '3.9'

services:
  app:
    build: .
    container_name: nest-app
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    depends_on: 
      - redis
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo-db
    restart: unless-stopped
    ports:
      - "${MONGOOSE_PORT:-27018}:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7
    container_name: redis-cache
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6378}:6379"

volumes:
  mongo-data:
